package com.example.inventory.adapter;

import android.content.ContentValues;
import android.content.Context;
import android.content.Intent;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.pdf.PdfDocument;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.inventory.R;
// Make sure this imports YOUR InventoryItem model correctly
import com.example.inventory.model.InventoryItem;

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;

public class ReportAdapter extends RecyclerView.Adapter<ReportAdapter.ViewHolder> {

    private List<InventoryItem> list;

    public ReportAdapter(List<InventoryItem> list) {
        this.list = list;
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        // Inflates the modern "Ticket" style row layout
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_report_row, parent, false);
        return new ViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        InventoryItem item = list.get(position);

        // 1. Bind Basic Data
        holder.tvName.setText(item.getName());
        holder.tvPrice.setText("$" + String.format("%.2f", item.getPrice()));

        // Handle Date (Prevent crash if date is missing)
        if(item.getDateAdded() != null) {
            holder.tvDate.setText("Added: " + item.getDateAdded());
        } else {
            holder.tvDate.setText("Date: N/A");
        }

        // --- BUTTON ACTIONS ---

        // 2. SHARE BUTTON LOGIC (Replaces Print)
        holder.btnPrint.setOnClickListener(v -> {
            // Prepare text
            String shareBody = "INVENTORY REPORT\n" +
                    "----------------\n" +
                    "Product: " + item.getName() + "\n" +
                    "Price: $" + item.getPrice() + "\n" +
                    "Quantity: " + item.getQuantity() + "\n" +
                    "Date: " + (item.getDateAdded() != null ? item.getDateAdded() : "N/A");

            // Create Intent
            Intent sharingIntent = new Intent(Intent.ACTION_SEND);
            sharingIntent.setType("text/plain");
            sharingIntent.putExtra(Intent.EXTRA_SUBJECT, "Report: " + item.getName());
            sharingIntent.putExtra(Intent.EXTRA_TEXT, shareBody);

            // Launch Share Sheet
            v.getContext().startActivity(Intent.createChooser(sharingIntent, "Share via"));
        });

        // 3. SAVE PDF BUTTON LOGIC
        holder.btnSave.setOnClickListener(v -> {
            generatePDF(v.getContext(), item);
        });
    }

    @Override
    public int getItemCount() { return list.size(); }

    // --- PDF GENERATION LOGIC ---
    private void generatePDF(Context context, InventoryItem item) {
        // Create Document
        PdfDocument document = new PdfDocument();
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(595, 842, 1).create();
        PdfDocument.Page page = document.startPage(pageInfo);
        Canvas canvas = page.getCanvas();
        Paint paint = new Paint();

        // Draw Title
        paint.setColor(Color.BLACK);
        paint.setTextSize(24);
        paint.setFakeBoldText(true);
        canvas.drawText("INVENTORY REPORT", 50, 60, paint);

        // Draw Subtitle
        paint.setTextSize(14);
        paint.setColor(Color.DKGRAY);
        paint.setFakeBoldText(false);
        canvas.drawText("Generated by Inventify App", 50, 85, paint);

        // Draw Line
        paint.setColor(Color.LTGRAY);
        paint.setStrokeWidth(2);
        canvas.drawLine(50, 100, 545, 100, paint);

        // Draw Details
        paint.setColor(Color.BLACK);
        paint.setTextSize(18);
        int y = 150;

        canvas.drawText("Product Name: " + item.getName(), 50, y, paint);
        y += 40;
        canvas.drawText("Price: $" + item.getPrice(), 50, y, paint);
        y += 40;
        canvas.drawText("Quantity: " + item.getQuantity(), 50, y, paint);
        y += 40;
        String date = (item.getDateAdded() != null) ? item.getDateAdded() : "Unknown";
        canvas.drawText("Date Added: " + date, 50, y, paint);

        // Footer
        paint.setTextSize(12);
        paint.setColor(Color.GRAY);
        canvas.drawText("This document is an official record.", 50, 800, paint);

        document.finishPage(page);

        // Save File to Downloads
        String fileName = "Report_" + item.getName() + "_" + System.currentTimeMillis() + ".pdf";

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                // Modern Android (10+)
                ContentValues values = new ContentValues();
                values.put(MediaStore.MediaColumns.DISPLAY_NAME, fileName);
                values.put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf");
                values.put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS);

                Uri uri = context.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, values);
                if (uri != null) {
                    OutputStream outputStream = context.getContentResolver().openOutputStream(uri);
                    document.writeTo(outputStream);
                    if (outputStream != null) outputStream.close();
                    Toast.makeText(context, "Saved to Downloads: " + fileName, Toast.LENGTH_LONG).show();
                }
            } else {
                // Older Android (9 and below)
                String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString();
                java.io.File file = new java.io.File(path, fileName);
                document.writeTo(new java.io.FileOutputStream(file));
                Toast.makeText(context, "Saved to: " + file.getAbsolutePath(), Toast.LENGTH_LONG).show();
            }
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(context, "Error saving PDF: " + e.getMessage(), Toast.LENGTH_SHORT).show();
        }

        document.close();
    }

    public static class ViewHolder extends RecyclerView.ViewHolder {
        TextView tvName, tvDate, tvPrice;
        ImageView btnPrint, btnSave;

        public ViewHolder(@NonNull View itemView) {
            super(itemView);
            tvName = itemView.findViewById(R.id.tvReportName);
            tvDate = itemView.findViewById(R.id.tvReportDate);
            tvPrice = itemView.findViewById(R.id.tvReportPrice);
            btnPrint = itemView.findViewById(R.id.btnPrint); // This is the Share Button
            btnSave = itemView.findViewById(R.id.btnSave);   // This is the PDF Button
        }
    }
}